apiVersion: apps/v1
kind: Deployment
metadata:
  name: nti-django-deployment 
spec:
  replicas: 4
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django 
    spec:
      containers:
      - name: django-container
        image: 992382364418.dkr.ecr.us-east-1.amazonaws.com/nti-project
        volumeMounts:
          - name: config-volume
            mountPath: /etc/config
      volumes:
        - name: config-url 
          configMap:
            name: database-config
