version: "3.8"

services:
  nginx:
    build: ./nginx
    image: nginx
    container_name: "nginx"
    ports:
      - 80:80
    depends_on:
      - django_app
  django_app:
    image: django_app
    build:
      context: ./django
    container_name: "django"
    ports:
      - 8001:8001
    command: gunicorn core.wsgi --bind 0.0.0.0:8001
    env_file:
      - "./django/.env"
    depends_on:
      - db
  db:
    image: mysql
    container_name: "database"
    environment:
      - MYSQL_ROOT_PASSWORD=P@ss0rd 
      - MYSQL_DATABASE=django_db 
    volumes:
      - ./data/mysql/db:/var/lib/mysql
